# Generated by Django 5.1 on 2024-10-11 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipe", "0002_category_recipe"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="cooking_time",
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="description",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="ingredients",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="preparation_steps",
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
