# Generated by Django 5.1 on 2024-10-11 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipe", "0003_alter_recipe_cooking_time_alter_recipe_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="cooking_time",
            field=models.DateField(),
        ),
    ]
