# Generated by Django 5.1 on 2024-10-11 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipe", "0004_alter_recipe_cooking_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="user_id",
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
