# Generated by Django 5.1 on 2024-10-11 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipe", "0007_alter_recipes_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipes",
            name="user_id",
        ),
        migrations.AddField(
            model_name="recipes",
            name="owner",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name="recipes",
            name="cooking_time",
            field=models.DateField(auto_now_add=True),
        ),
    ]
