# Generated by Django 5.1 on 2024-10-11 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipe", "0012_alter_recipes_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipes",
            name="serving_size",
            field=models.IntegerField(default=1),
        ),
    ]
